---
repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes
        # - id: identity  # Prints all files passed to pre-commits. Debugging.
  - repo: https://github.com/lyz-code/yamlfix
    rev: 1.9.0
    hooks:
      - id: yamlfix
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args:
          - --maxkb=1300
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
        types:
          - text
      - id: forbid-submodules
      - id: mixed-line-ending
        args:
          - --fix=lf
        description: Forces to replace line ending by the UNIX 'lf' character.
      - id: trailing-whitespace
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.31.0
    hooks:
      - id: yamllint
          # - repo: https://github.com/psf/black
          #   rev: 23.3.0
          #   hooks:
          #     - id: black
          #       language_version: python3.10
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.267
    hooks:
      - id: ruff
      #   args:
      #     - --verbose
  # - repo: https://github.com/kynan/nbstripout
  #   rev: 0.6.1
  #   hooks:
  #     - id: nbstripout
  #       args:
  #         - --extra-keys
  #         - metadata.kernelspec metadata.language_info.version metadata.vscode
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
      - id: nbqa-black
      - id: nbqa-ruff
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-black
        args:
          - --wrap
          - '88'
        files: (README\.md)
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-myst
          - mdformat-black
        args:
          - --wrap
          - '88'
        files: (docs/.)
ci:
  autoupdate_schedule: monthly
