---
name: metrics
channels:
  - conda-forge
  - r
dependencies:
  - python==3.12
  - click
  - estimagic
  - joblib
  - jupyterlab
  - linearmodels
  - matplotlib
  - numpy
  - openpyxl
  - pandas
  - pdbpp
  - plotly
  - pyarrow
  - pytask
  - pytest
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - rpy2
  - jax
  - pre-commit
