---
name: metrics
channels:
  - conda-forge
dependencies:
  - python=3.11
  - click==8.1.3
  - joblib==1.2.0
  - jupyterlab==3.6.2
  - matplotlib==3.7.1
  - numpy==1.24.2
  - openpyxl==3.1.1
  - pandas==1.5.3
  - pdbpp==0.10.3
  - pip==23.0.1
  - plotly==5.14.0
  - pyarrow==11.0.0
  - pytask==0.3.1
  - pytest==7.2.2
  - seaborn==0.12.2
  - scipy==1.10.1
  - statsmodels==0.13.5
  - linearmodels==4.27
  - pip:
      - pre-commit==3.2.1
