[tool.ruff]
target-version = "py310"
fix = true
select = ["ALL"]
extend-ignore = [
    "E402",
    "PLR2004",

    # missing type annotation
    "ANN001",

    # missing type annotation for `*args`
    "ANN002",

    # missing type annotation for `**kwargs`
    "ANN003",

    # missing return type annotation for public function
    "ANN201",

    # missing return type annotation for private function
    "ANN202",

    # Missing docstring in public module
    "D100",

    # missing docstring in public function
    "D103",

    # missing docstring in public package
    "D104",

    # exception must not use a string literal
    "EM101",

    # exception must not use an f-string literal
    "EM102",

    # Too many arguments to function call
    "PLR0913",

    # use of `assert` detected
    "S101",

    # long messages outside the exception class
    "TRY003",

    # part of implicit name pacakge
    "INP001",

]

[tool.ruff.per-file-ignores]

[tool.ruff.pydocstyle]
convention = "google"


[tool.nbqa.config]
black = "pyproject.toml"

[tool.nbqa.mutate]
black = 1

[tool.yamlfix]
line_length = 88
sequence_style = "block_style"
none_representation = "null"
